spring:
  application:
    name: navigation-backend

  # 数据源配置
  datasource:
    # 开发环境使用H2数据库
    url: jdbc:h2:mem:navigationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

    # 生产环境使用MySQL（取消注释）
    # url: jdbc:mysql://localhost:3306/navigation_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # username: root
    # password: your_password

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        # 生产环境使用MySQL方言（取消注释）
        # dialect: org.hibernate.dialect.MySQL8Dialect

  # H2控制台配置
  h2:
    console:
      enabled: true
      path: /h2-console

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: xingchen-navigation-secret-key-2024-change-in-production
  expiration: 86400000  # 24小时（毫秒）
  refresh-expiration: 604800000  # 7天（毫秒）

# CORS配置
cors:
  allowed-origins: http://localhost:*,http://127.0.0.1:*,file://
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

# 日志配置
logging:
  level:
    com.xingchen.navigation: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG